name: React App build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 2 * * *"   # periodic run
  workflow_dispatch:       # Manual trigger

jobs:
  #Build & Test Job
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --ci --reporters=default --reporters=jest-junit  #npm test -- --ci --reporters=default --reporters=jest-junit --outputFile=test-results/junit.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/

